name: py3.9
channels:
  - defaults
  - conda-forge
dependencies:
  # - _libgcc_mutex=0.1 # linux-specific package
  # - _openmp_mutex=5.1 # linux-specific package
  - ca-certificates=2024.9.24
  # - ld_impl_linux-64=2.40 # linux-specific package
  - libffi=3.3
  # - libgcc-ng=11.2.0 # linux-specific package
  # - libgomp=11.2.0 # linux-specific package
  # - libstdcxx-ng=11.2.0 # linux-specific package
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=24.2
  - python=3.9.7
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - anndata==0.8.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - cached-property==1.5.2
      - cell2location==0.1
      - chex==0.1.7
      - comm==0.2.2
      - cycler==0.12.1
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.5.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - filelock==3.16.1
      - flax==0.7.4
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - future==1.0.0
      - grpcio==1.66.2
      - h5py==3.12.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jax==0.4.6
      - jax-cuda12-pjrt==0.4.23
      - jax-cuda12-plugin==0.4.23
      - jaxlib==0.4.6
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.7
      - llvmlite==0.39.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numba==0.56.4
      - numpy==1.22.0
      - numpyro==0.12.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.1
      - orbax-checkpoint==0.1.6
      - packaging==24.1
      - pandas==1.3.4
      - parso==0.8.4
      - patsy==0.5.6
      - pexpect==4.9.0
      - pillow==10.4.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydeprecate==0.3.1
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.1.4
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.5.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - rich==13.9.2
      - scanpy==1.9.1
      - scikit-learn==1.5.2
      - scipy==1.7.1
      - scvi-tools==0.16.2
      - seaborn==0.11.2
      - session-info==1.0.0
      - six==1.16.0
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - sympy==1.13.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.60
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchmetrics==1.4.2
      - torchvision==0.19.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - umap-learn==0.5.6
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - yarl==1.13.1
      - zipp==3.20.2
